### ISSUE TITLE
Plugin fails if LESS file has includes

### ISSUE THREAD

**Issue by bennycode** [marceloverdijk/lesscss-maven-plugin#45]
I use the plugin in my Java EE web app (thank you for that!) but it fails if the LESS file (which should be compiled) uses @import declarations.

For example:
@import url("http://fonts.googleapis.com/css?family=Open+Sans:600,700,400");

The error message is:

Error compiling LESS source
java.io.FileNotFoundException: File Q:\dev\projects\wlc\wlc-webapp\src\main\webapp\WEB-INF\frontend\less\http:\fonts.googleapis.com\css?family=Open+Sans:600,700,400.less not found.

**Comment by enricopulatzo** [comment]
This is actually not the maven plugin's fault; LESS expects remote URLs to end in .css.

The workaround is to add a fake query parameter to the imported url: e.g. @import url("//fonts.googleapis.com/css?family=Lato:400,700,900,400italic&.css");

The "&.css" shouldn't adversely affect your URL and your stylesheet will be imported without any issue.

**Comment by bennycode** [comment]
Thanks for the info! This has helped!
