### ISSUE TITLE
1.7.0.1.0 Release

### ISSUE THREAD

**Issue by sandroboehme** [marceloverdijk/lesscss-maven-plugin#50]
As promised I'm now working on syncing my fork (de.sandroboehme.lesscss:lesscss-maven-plugin:1.6.1.1.0 from https://github.com/sandroboehme/lesscss-maven-plugin) back to this project.

The next version will be `org.lesscss:lesscss-maven-plugin:1.7.0.1.0` as it is the 1.0 release for less 1.7.0 (Rhino based).

The currently pushed code fixes the following issues:
- added dependency to `org.lesscss:lesscss:1.7.0.1.0`
- #12 (Watch mode)
- #36 (Added node executable path to NodeJsLessCompiler constructor)
- #25 (Added force parameter handling on Mojo configuration as described by dfernandez79) 
- #17 (Add "skip" configuration option issue)
- #7 (Fix for force=true issue) 
- #16 (Add support for output file suffixes)
- #49 (Adding outputFileFormat parameter)
  The last two issues have been merged. The code now contains the integration tests from #16 and the unit test, `README.md` update, and file prefix feature of  #49.

You can now test the plugin by running the automatic tests and by installing and trying it. Please let me know if everything works fine or if there are problems that prevent a release. I will not start a release in the next week to provide time for testing.

Best,

Sandro

**Comment by tnodev** [comment]
Hello,

is there a snapshot repository to get and test the plugin ?

thanks, Thomas

**Comment by sandroboehme** [comment]
Hi Thomas,

no there isn't. Do you see an advantage to checking it out and installing it locally?

Best,
Sandro

**Comment by sandroboehme** [comment]
The release is available now. 
http://search.maven.org/#search|ga|1|org.lesscss
Enjoy!

**Comment by tnodev** [comment]
Thanks, because pb with maven2 !

**Comment by sandroboehme** [comment]
What do you mean with "pb"?

**Comment by tnodev** [comment]
Pb with maven-shade-plugin: Plugin requires Maven version 3.0

**Comment by sandroboehme** [comment]
Ah ok. I guess "pb" means problem. :-) I just didn't know that. If you want, you can have a look at https://github.com/marceloverdijk/lesscss-java/pull/15 to see what the background is about that decision.

**Comment by sandroboehme** [comment]
But you are right, we didn't took it into consideration, that the plugin requires Maven 3
