### ISSUE TITLE
add "skip" configuration option

### ISSUE THREAD

**Issue by trumbitta** [marceloverdijk/lesscss-maven-plugin#9]
It would be very useful in complex projects (and in my own, of course :) ) to be able to skip the execution of the lesscss-maven-plugin if a property is set to true.

Just as in derby-maven-plugin and in the testing family of plugins (surefire, junit, you know...)

``` xml
....
<configuration>
....
    <skip>${myProperty}</skip> <!-- <skip>true</skip> or <skip>false</skip> -->
...
</configuration>
```

I guess that copying from those plugins that already have a skip mechanism would even be a breeze!
I'd submit a pull-request myself if I was a better Java developer!

**Comment by lgrammel** [comment]
I would need this feature for one of my projects as well - it would enable me to reduce the build time of my initial unit testing job on the CI server.
